name: crackuplib
description: Library for getting and parsing jokes from <a href="https://upjoke.com/" target="_blank">upjoke.com</a>
version: 1.0.0
repository: "https://github.com/mattheroit/crackuplib"
issue_tracker: "https://github.com/mattheroit/crackuplib/issues"

environment:
  sdk: ^3.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  http: ^1.1.0
  html: ^0.15.4
